<?xml version="1.0" encoding="UTF-8"?>
<xsl:stylesheet version="2.0" 
    xmlns:html="http://www.w3.org/TR/REC-html40"
    xmlns:image="http://www.google.com/schemas/sitemap-image/1.1"
    xmlns:sitemap="http://www.sitemaps.org/schemas/sitemap/0.9"
    xmlns:xsl="http://www.w3.org/1999/XSL/Transform">
<xsl:output method="html" version="1.0" encoding="UTF-8" indent="yes"/>
<xsl:template match="/">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
<title>XML Sitemap | Premium Tools Hub</title>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
<style type="text/css">
  body {
    font-family: -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, Oxygen-Sans, Ubuntu, Cantarell, "Helvetica Neue", sans-serif;
    color: #334155;
    margin: 0;
  }
  #header {
    background-color: #3B82F6;
    padding: 30px;
    color: #fff;
  }
  #header h1 {
    margin: 0;
    font-size: 24px;
    font-weight: 600;
  }
  #header p {
    margin: 10px 0 0 0;
    font-size: 14px;
    color: #DBEAFE;
  }
  #header a {
    color: #fff;
    text-decoration: underline;
  }
  #content {
    max-width: 1000px;
    margin: 0 auto;
    padding: 30px 20px;
  }
  p.desc {
    margin-bottom: 20px;
    font-size: 14px;
    color: #64748B;
  }
  table {
    width: 100%;
    border-collapse: collapse;
    font-size: 13px;
  }
  th {
    text-align: left;
    padding: 12px 15px;
    background-color: #3B82F6;
    color: #fff;
    font-weight: 600;
  }
  th:first-child {
    border-top-left-radius: 4px;
  }
  th:last-child {
    border-top-right-radius: 4px;
  }
  td {
    padding: 12px 15px;
    border-bottom: 1px solid #E2E8F0;
  }
  tr:nth-child(even) td {
    background-color: #F8FAFC;
  }
  tr:hover td {
    background-color: #F1F5F9;
  }
  td a {
    color: #0284C7;
    text-decoration: none;
  }
  td a:hover {
    text-decoration: underline;
  }
</style>
</head>
<body>
  <div id="header">
    <h1>XML Sitemap</h1>
    <p>
      This XML Sitemap is generated by <strong>Premium Tools Hub</strong>. It is what search engines like Google use to crawl and re-crawl posts/pages/products on your website.<br/>
      Learn more about <a href="https://sitemaps.org" target="_blank" rel="noopener noreferrer">XML Sitemaps</a>.
    </p>
  </div>
  <div id="content">
    <xsl:if test="count(sitemap:sitemapindex/sitemap:sitemap) &gt; 0">
      <p class="desc">
        This XML Sitemap Index file contains <strong><xsl:value-of select="count(sitemap:sitemapindex/sitemap:sitemap)"/></strong> sitemaps.
      </p>
      <table>
        <thead>
          <tr>
            <th width="70%">Sitemap</th>
            <th width="30%">Last Modified</th>
          </tr>
        </thead>
        <tbody>
        <xsl:for-each select="sitemap:sitemapindex/sitemap:sitemap">
          <xsl:variable name="sitemapURL">
            <xsl:value-of select="sitemap:loc"/>
          </xsl:variable>
          <tr>
            <td>
              <a href="{$sitemapURL}"><xsl:value-of select="sitemap:loc"/></a>
            </td>
            <td>
              <xsl:value-of select="concat(substring(sitemap:lastmod,0,11),concat(' ', substring(sitemap:lastmod,12,5)),concat(' ', substring(sitemap:lastmod,20,6)))"/>
            </td>
          </tr>
        </xsl:for-each>
        </tbody>
      </table>
    </xsl:if>
    <xsl:if test="count(sitemap:sitemapindex/sitemap:sitemap) &lt; 1">
      <p class="desc">
        This XML Sitemap contains <strong><xsl:value-of select="count(sitemap:urlset/sitemap:url)"/></strong> URLs.
      </p>
      <table>
        <thead>
          <tr>
            <th width="70%">URL</th>
            <th width="15%">Priority</th>
            <th width="15%">Change Frequency</th>
          </tr>
        </thead>
        <tbody>
          <xsl:variable name="lower" select="'abcdefghijklmnopqrstuvwxyz'"/>
          <xsl:variable name="upper" select="'ABCDEFGHIJKLMNOPQRSTUVWXYZ'"/>
          <xsl:for-each select="sitemap:urlset/sitemap:url">
            <tr>
              <td>
                <xsl:variable name="itemURL">
                  <xsl:value-of select="sitemap:loc"/>
                </xsl:variable>
                <a href="{$itemURL}">
                  <xsl:value-of select="sitemap:loc"/>
                </a>
              </td>
              <td>
                <xsl:value-of select="concat(sitemap:priority*100,'%')"/>
              </td>
              <td>
                <xsl:value-of select="concat(translate(substring(sitemap:changefreq, 1, 1),concat($lower, $upper),concat($upper, $lower)),substring(sitemap:changefreq, 2))"/>
              </td>
            </tr>
          </xsl:for-each>
        </tbody>
      </table>
    </xsl:if>
  </div>
</body>
</html>
</xsl:template>
</xsl:stylesheet>
